### ISSUE TITLE
Solving for SAMEORIGIN problem in iframe

### ISSUE THREAD

**Issue by nrosella** [waterlink/rack-reverse-proxy#18]
Hi

I'm a Rails noob and this is my first intro to proxies so go light on me :)

I'm trying to use this gem to display a site (google.com in this case) that has a "X-Frame-Options: SAMEORIGIN" header response inside an iframe. I suppose I'm trying to go for something like this but without having to touch nginx (for now): http://distinctplace.com/infrastructure/2013/10/14/internal-redirect-to-another-domain-with-proxy_pass-and-nginx/

The iframe currently sits in the `users/:id` view.

Now if I do:
```
config.middleware.insert_before(Rack::Runtime, Rack::ReverseProxy) do 
      reverse_proxy_options preserve_host: true
      reverse_proxy '/users', 'http://google.com'
end
```

then this obviously redirects `localhost:3000/users` to google.com/users -- not exactly what I'm after!

To be honest I don't really know where to go from here :/

Any help or direction that you could give to make me able to render google.com in an iframe would be brilliant! I'm only trying to display the site - I don't need to be logging into an app through the iframe etc.

Thanks in advance

Nino

**Comment by waterlink** [comment]
Currently there is no way to override `X-Frame-Options`. One way is to include such option in `rack-reverse-proxy`. Other way is to add custom small (5-10 lines class) middleware on top in your application.

I will look into these possibilities a bit later today.

**Comment by nrosella** [comment]
That's great. Thanks

**Comment by waterlink** [comment]
Addressing first thing about not being fetch just `google.com`, but always fetching `google.com/users`. Currently `rack-reverse-proxy` will use the same url path that original request has. It will allow you to change, if you use regexp subcaptures:

```ruby
use Rack::ReverseProxy do
  # see here              v  v                            and here              v v
  reverse_proxy %r{/users/(.*)$}, "http://some-resource.example.org/api/v4/users/$1.json"
end
```

To achieve what you try to achieve, you would have to use a workaround with having a empty subcapture:

```ruby
use Rack::ReverseProxy do
  # see here                v v     and here        v v
  reverse_proxy %r{/users/.*($)}, "http://google.com/$1"
end
```

Since `($)` subcapture will always render an empty string `""`, you will get url "http://google.com/" always whenever the regex matches.

**Comment by waterlink** [comment]
Second thing that you will bump upon are redirects that any resource (and google including) does. Each redirect inside of iframe will go to the original website instead of yours. And will hit `X-Frame-Options` again, even if you modify them. One thing that you could do is to somehow capture redirect responses on the server and follow them automatically.

**Comment by waterlink** [comment]
For example this works for me, because I forced my URL be non-redirect one, but it might be not the case for you:

```ruby
require "rack/reverse_proxy"

class FrameOptionsMiddleware
  def initialize(app = nil)
    @app = app || -> _ { [404, {}, []] }
  end

  def call(env)
    resp = @app.call(env)
    resp[1]["X-Frame-Options"] = "ALLOW"
    resp
  end
end

use FrameOptionsMiddleware

use Rack::ReverseProxy do
  reverse_proxy_options preserve_host: true
  reverse_proxy %r{^/users/.*($)}, "https://www.google.de/$1"
end

app = proc do |env|
  [ 200, {"Content-Type" => "text/html"},
    ["<iframe src=/users/1></iframe>"],
  ]
end

run app
```

**Comment by waterlink** [comment]
Of course all the images and every other resource will be missing from the page, since it will try to download it from your server.

**Comment by waterlink** [comment]
So I would say, that it is not very reasonable thing to do.
